
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Tabla_simbolos {
  /* terminals */
  public static final int r_float = 8;
  public static final int s_mayor_que = 28;
  public static final int libreria = 40;
  public static final int s_incremento = 30;
  public static final int r_else = 6;
  public static final int r_switch = 12;
  public static final int s_llave_abrir = 35;
  public static final int identificador = 39;
  public static final int s_division = 25;
  public static final int s_decremento = 31;
  public static final int s_mayor_igual = 21;
  public static final int s_menor_que = 29;
  public static final int r_char_asterisco = 4;
  public static final int s_resta = 20;
  public static final int s_suma = 19;
  public static final int numero = 41;
  public static final int s_menor_igual = 22;
  public static final int s_comilla = 16;
  public static final int r_if = 9;
  public static final int EOF = 0;
  public static final int s_igual = 14;
  public static final int r_int = 10;
  public static final int error = 1;
  public static final int s_coma = 18;
  public static final int r_for = 7;
  public static final int s_llave_cerrar = 36;
  public static final int r_importar = 2;
  public static final int r_char = 3;
  public static final int s_parentesis_abrir = 37;
  public static final int s_parentesis_cerrar = 38;
  public static final int s_restar_a = 33;
  public static final int s_diferencia = 24;
  public static final int s_multiplicar_a = 34;
  public static final int s_dos_puntos = 15;
  public static final int s_multiplicacion = 26;
  public static final int s_sumar_a = 32;
  public static final int s_comparacion = 23;
  public static final int s_porcentaje = 27;
  public static final int r_main = 11;
  public static final int s_punto_coma = 17;
  public static final int r_while = 13;
  public static final int r_do = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "r_importar",
  "r_char",
  "r_char_asterisco",
  "r_do",
  "r_else",
  "r_for",
  "r_float",
  "r_if",
  "r_int",
  "r_main",
  "r_switch",
  "r_while",
  "s_igual",
  "s_dos_puntos",
  "s_comilla",
  "s_punto_coma",
  "s_coma",
  "s_suma",
  "s_resta",
  "s_mayor_igual",
  "s_menor_igual",
  "s_comparacion",
  "s_diferencia",
  "s_division",
  "s_multiplicacion",
  "s_porcentaje",
  "s_mayor_que",
  "s_menor_que",
  "s_incremento",
  "s_decremento",
  "s_sumar_a",
  "s_restar_a",
  "s_multiplicar_a",
  "s_llave_abrir",
  "s_llave_cerrar",
  "s_parentesis_abrir",
  "s_parentesis_cerrar",
  "identificador",
  "libreria",
  "numero"
  };
}

